### ISSUE TITLE
在？更新下？

### ISSUE THREAD

**Issue by ltxhhz** [koishijs/QFace#6]
而且 `15` 号和 `193` 号还出不来

**Comment by shigma** [comment]
我看看……除了这俩还有什么要更新的吗？

**Comment by ltxhhz** [comment]
![IMG_20220510_191408.jpg](https://user-images.githubusercontent.com/51697596/167616295-171c6edb-5e30-4212-a934-88d50dd0b288.jpg)
还有这些是324号到336号，实在找不到别的地方获取这些高清图。。

**Comment by ltxhhz** [comment]
我找到了[更合适的](https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/tree/development/icalingua/static/face)

**Comment by shigma** [comment]
草，以后就去这更新了（

**Comment by ltxhhz** [comment]
> 草，以后就去这更新了（

群友贡献的 ;-)

**Comment by shigma** [comment]
我之前也是找了朋友帮忙拆包，不过现在好像是忘记方法了就没法更新……

总之感谢指路，我去问问 Icalingua 那边吧。
